### ISSUE TITLE
Trouble running the project

### ISSUE THREAD

**Issue by theighost** [kishikawakatsumi/ScreenRecorder#6]
Hello,

Sorry for the stupid question, I tried running the project included in this download, but when I try to run the simulator in xcode I get this gibberish:

> 2016-08-28 15:53:18.568 ScreenRecorder[1321:38408] -[UIScreen _boundsInPixels]: unrecognized selector sent to instance 0x7f823ac0c640
> 2016-08-28 15:53:18.571 ScreenRecorder[1321:38408] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIScreen _boundsInPixels]: unrecognized selector sent to instance 0x7f823ac0c640'
> **\* First throw call stack:
> (
>     0   CoreFoundation                      0x000000011147ee65 __exceptionPreprocess + 165
>     1   libobjc.A.dylib                     0x0000000110ef7deb objc_exception_throw + 48
>     2   CoreFoundation                      0x000000011148748d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
>     3   CoreFoundation                      0x00000001113d490a ___forwarding___ + 970
>     4   CoreFoundation                      0x00000001114802d8 **forwarding_prep_1_** + 120
>     5   ScreenRecorder                      0x000000010ec21b41 -[SRScreenRecorder setupAssetWriterWithURL:] + 801
>     6   ScreenRecorder                      0x000000010ec2269a -[SRScreenRecorder startRecording] + 74
>     7   ScreenRecorder                      0x000000010ec1f35a -[SRAppDelegate application:didFinishLaunchingWithOptions:] + 122
>     8   UIKit                               0x000000010ecdb1f1 -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 272
>     9   UIKit                               0x000000010ecdc397 -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 3415
>     10  UIKit                               0x000000010ece2cc6 -[UIApplication _runWithMainScene:transitionContext:completion:] + 1760
>     11  UIKit                               0x000000010ecdfe7b -[UIApplication workspaceDidEndTransaction:] + 188
>     12  FrontBoardServices                  0x00000001119a1754 -[FBSSerialQueue _performNext] + 192
>     13  FrontBoardServices                  0x00000001119a1ac2 -[FBSSerialQueue _performNextFromRunLoopSource] + 45
>     14  CoreFoundation                      0x00000001113aaa31 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
>     15  CoreFoundation                      0x00000001113a095c __CFRunLoopDoSources0 + 556
>     16  CoreFoundation                      0x000000011139fe13 __CFRunLoopRun + 867
>     17  CoreFoundation                      0x000000011139f828 CFRunLoopRunSpecific + 488
>     18  UIKit                               0x000000010ecdf7cd -[UIApplication _run] + 402
>     19  UIKit                               0x000000010ece4610 UIApplicationMain + 171
>     20  ScreenRecorder                      0x000000010ec1f2af main + 111
>     21  libdyld.dylib                       0x00000001157a792d start + 1
>     22  ???                                 0x0000000000000001 0x0 + 1
> )
> libc++abi.dylib: terminating with uncaught exception of type NSException
> (lldb) 

No errors seem to appear in the code though.

And another stupid one, can this library monitor any app opened in the IOS device or is thought to be incorporated into the app for which I want to record? (Say I want to record how I navigate through apps, facebook, whatsapp..etc)

**Comment by longshao521** [comment]
look out this "#ifndef APPSTORE_SAFE"

**Comment by ChickChik** [comment]
[UIScreen _boundsInPixels] not work on new ios version
